// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhfzkeonklgyuqxhrjky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZnprZW9ua2xneXVxeGhyamt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTc3MDUsImV4cCI6MjA3NDI5MzcwNX0.MapxagnsYd-GnAcRGNtha1CMkgTeJhJ4pcq_CLlvHzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});